name: binder
description: A lightweight, yet powerful way to bind your application state with your business logic.
version: 0.5.0
homepage: https://github.com/letsar/binder

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.1
